import { HomePageFeaturedProduct } from "./product-api";

export const mockData: HomePageFeaturedProduct[] = [
    {
        id: 1,
        genericPartId: 1,
        genericPartNumber: "1234567890",
        familyId: 1,
        familyName: "Family A",
        familyNameEnglish: "Family A English",
        deviceDescription: "Device 1 description",
        releaseDate: new Date(),
        marketingStatusId: 1,
        marketingStatus: "Marketing Status 1",
        marketingStatusDescription: "Marketing Status 1 description",   
        newFlag: true,
        partImageAvailable: true,
        partImageUrl: "https://placehold.co/150/png",
        gpnUrl: "https://placehold.co/150/png",
        language: "en-US",
        datasheetUrl: "https://placehold.co/150/png",
        currency: "USD",
        displayQuantity: "100",
        approximatePrice: "100",
        selectionToolUrl: "https://placehold.co/150/png",
        altText: "Alt Text 1",
    },
    {
        id: 2,
        genericPartId: 2,
        genericPartNumber: "1234567890",
        familyId: 2,
        familyName: "Family A",
        familyNameEnglish: "Family A English",
        deviceDescription: "Device 2 description",
        releaseDate: new Date(),
        marketingStatusId: 2,
        marketingStatus: "Marketing Status 2",  
        marketingStatusDescription: "Marketing Status 2 description",
        newFlag: false,
        partImageAvailable: false,
        partImageUrl: "https://placehold.co/150/png",
        gpnUrl: "https://placehold.co/150/png",
        language: "en-US",
        datasheetUrl: "https://placehold.co/150/png",
        currency: "CAD",
        displayQuantity: "100",
        approximatePrice: "100",
        selectionToolUrl: "https://placehold.co/150/png",
        altText: "Alt Text 2",
    },
    {
        id: 3,
        genericPartId: 3,
        genericPartNumber: "1234567890",
        familyId: 3,    
        familyName: "Family A",
        familyNameEnglish: "Family A English",
        deviceDescription: "Device 3 description",
        releaseDate: new Date(),
        marketingStatusId: 3,
        marketingStatus: "Marketing Status 3",
        marketingStatusDescription: "Marketing Status 3 description",
        newFlag: false,
        partImageAvailable: false,
        partImageUrl: "https://placehold.co/150/png",
        gpnUrl: "https://placehold.co/150/png",
        language: "en-US",
        datasheetUrl: "https://placehold.co/150/png",
        currency: "CAD",
        displayQuantity: "100",
        approximatePrice: "100",
        selectionToolUrl: "https://placehold.co/150/png",
        altText: "Alt Text 3",
    },
    {
        id: 4,
        genericPartId: 4,
        genericPartNumber: "1234567890",
        familyId: 4,
        familyName: "Family B",
        familyNameEnglish: "Family B English",
        deviceDescription: "Device 4 description",
        releaseDate: new Date(),
        marketingStatusId: 4,
        marketingStatus: "Marketing Status 4",
        marketingStatusDescription: "Marketing Status 4 description",
        newFlag: true,
        partImageAvailable: false,
        partImageUrl: "https://placehold.co/150/png",
        gpnUrl: "https://placehold.co/150/png",
        language: "en-US",
        datasheetUrl: "https://placehold.co/150/png",
        currency: "USD",
        displayQuantity: "100",
        approximatePrice: "100",
        selectionToolUrl: "https://placehold.co/150/png",
        altText: "Alt Text 4",
    },
    {
        id: 5,
        genericPartId: 5,
        genericPartNumber: "1234567890",
        familyId: 5,
        familyName: "Family B",
        familyNameEnglish: "Family B English",
        deviceDescription: "Device 5 description",
        releaseDate: new Date(),
        marketingStatusId: 5,
        marketingStatus: "Marketing Status 5",
        marketingStatusDescription: "Marketing Status 5 description",
        newFlag: true,
        partImageAvailable: false,
        partImageUrl: "https://placehold.co/150/png",
        gpnUrl: "https://placehold.co/150/png",
        language: "en-US",
        datasheetUrl: "https://placehold.co/150/png",
        currency: "USD",
        displayQuantity: "100",
        approximatePrice: "100",
        selectionToolUrl: "https://placehold.co/150/png",
        altText: "Alt Text 5",
    },
    {
        id: 6,
        genericPartId: 6,
        genericPartNumber: "1234567890",
        familyId: 6,
        familyName: "Family B",
        familyNameEnglish: "Family B English",
        deviceDescription: "Device 6 description",
        releaseDate: new Date(),
        marketingStatusId: 6,
        marketingStatus: "Marketing Status 6",
        marketingStatusDescription: "Marketing Status 6 description",
        newFlag: false,
        partImageAvailable: false,
        partImageUrl: "https://placehold.co/150/png",
        gpnUrl: "https://placehold.co/150/png",
        language: "en-US",
        datasheetUrl: "https://placehold.co/150/png",
        currency: "USD",
        displayQuantity: "100",
        approximatePrice: "100",
        selectionToolUrl: "https://placehold.co/150/png",
        altText: "Alt Text 6",
    },
]