import { KEY_PREFIX } from "../constants";

// This is in separate file to avoid circular reference when pushing types
// Otherwise there's a confusing error about object is not iterable when doing an Opti push

export const AllComponentTypeKeyMap = {
  ArticlePageHeader: `${KEY_PREFIX}ArticlePageHeader_Component`,
  HeroComponent: `${KEY_PREFIX}Hero_Component`,
  ContentBlockComponent: `${KEY_PREFIX}ContentBlock_Component`,
  CtaLinkListComponent: `${KEY_PREFIX}CtaLinkList_Component`,
  CtaButtonListComponent: `${KEY_PREFIX}CtaButtonList_Component`,
  AccordionComponent: `${KEY_PREFIX}Accordion_Component`,
  AccordionPanelComponent: `${KEY_PREFIX}AccordionPanel_Component`,
  CardListComponent: `${KEY_PREFIX}CardList_Component`,
  SingleGeneralCardComponent: `${KEY_PREFIX}GeneralCard_Component`,
  GeneralCardsComponent: `${KEY_PREFIX}GeneralCards_Component`,
  ProductCardsComponent: `${KEY_PREFIX}ProductCards_Component`,
  CodeEmbedComponent: `${KEY_PREFIX}CodeEmbed_Component`,
  CodeSnippetComponent: `${KEY_PREFIX}CodeSnippet_Component`,
  HomePageBannerComponent: `${KEY_PREFIX}HomePageHeroSlide_Component`,
  HomePageBannerFolder: `${KEY_PREFIX}HomePageHeroSlide_Folder`,
  ColumnGridColumnComponent: `${KEY_PREFIX}ColumnGridColumn_Component`,
  ColumnGridComponent: `${KEY_PREFIX}ColumnGrid_Component`,
  NewProductsCardListComponent: `${KEY_PREFIX}NewProductsCardList_Component`,
  StandardImageComponent: `${KEY_PREFIX}StandardImage_Component`,
  HeadshotImageComponent: `${KEY_PREFIX}HeadshotImage_Component`,
  HorizontalRuleComponent: `${KEY_PREFIX}HorizontalRule_Component`,
  VideoPlayerComponent: `${KEY_PREFIX}VideoPlayer_Component`,
  SelectionToolComponent: `${KEY_PREFIX}SelectionTool_Component`,
  PremiumMediaHeadingComponent: `${KEY_PREFIX}PremiumMediaHeading_Component`,
  ScrollingStoryVertical: `${KEY_PREFIX}ScrollingStoryVertical_Component`,
  ScrollingStoryVerticalContent: `${KEY_PREFIX}ScrollingStoryVerticalContent_Component`,
  ApplicationSearchBoxComponent: `${KEY_PREFIX}ApplicationSearchBox_Component`,
  FAQSearchBoxComponent: `${KEY_PREFIX}FAQSearchBox_Component`,
  BrowseVideosComponent: `${KEY_PREFIX}BrowseVideos_Component`,
  HierarchyNavigationComponent: `${KEY_PREFIX}HierarchyNavigation_Component`,
  HierarchyNavigationItemComponent: `${KEY_PREFIX}HierarchyNavigationItem_Component`,
  TabsComponent: `${KEY_PREFIX}Tabs_Component`,
  GeneralTabComponent: `${KEY_PREFIX}GeneralTab_Component`,
  JumpLinkNavigationComponent: `${KEY_PREFIX}JumpLinkNavigation_Component`,
  JumpLinkNavigationHorizontalComponent: `${KEY_PREFIX}JumpLinkNavigationHorizontal_Component`,
  JumpLinkTargetComponent: `${KEY_PREFIX}JumpLinkTarget_Component`,
  KeyCustomerMessagesComponent: `${KEY_PREFIX}KeyCustomerMessages_ComponentType`,
  KeyCustomerMessageItemComponent: `${KEY_PREFIX}KeyCustomerMessageItem_ComponentType`,
  GoldenSourcePageHeading: `${KEY_PREFIX}GoldenSourcePageHeading_Component`,
  ApiSwaggerComponent: `${KEY_PREFIX}ApiSwagger_Component`,
  PartnerResourceFilterComponent: `${KEY_PREFIX}PartnerResourceFilter_Component`,
  PartnerResourceFilterOptionComponent: `${KEY_PREFIX}PartnerResourceFilterOption_Component`,
  HorizontalRuleContentDividerComponent: `${KEY_PREFIX}HorizontalRuleContentDivider_Component`,
  HorizontalRulePageDividerComponent: `${KEY_PREFIX}HorizontalRulePageDivider_Component`,
  LLCPromoFolder: `${KEY_PREFIX}LLCPromo_Folder`,
  LLCPromoComponent: `${KEY_PREFIX}LLCPromo_Component`,
  LLCPromoMessageComponent: `${KEY_PREFIX}LLCPromoMessage_Component`,
  LLCPromoWarningComponent: `${KEY_PREFIX}LLCPromoWarning_Component`,
  EventFolder: `${KEY_PREFIX}Event_Folder`,
  EventComponent: `${KEY_PREFIX}Event_Component`,
  FeaturedApplicationFolder: `${KEY_PREFIX}FeaturedApplication_Folder`,
  FeaturedApplicationComponent: `${KEY_PREFIX}FeaturedApplication_Component`,
  ApplicationStoryComponent: `${KEY_PREFIX}ApplicationStory_Component`,
  ApplicationSelectionToolComponent: `${KEY_PREFIX}ApplicationSelectionTool_Component`,
  ReferenceDesignSearchComponent: `${KEY_PREFIX}ReferenceDesignSearch_Component`,
  CodeFragmentComponent: `${KEY_PREFIX}CodeFragment_Component`,
  ImageComparisonComponent: `${KEY_PREFIX}ImageComparison_Component`,
  ImageComparisonItemComponent: `${KEY_PREFIX}ImageComparisonItem_Component`,
  TeaserComponent: `${KEY_PREFIX}Teaser_Component`,
  ApplicationCategoryListComponent: `${KEY_PREFIX}ApplicationCategoryList_Component`,
  ViewMoreComponent: `${KEY_PREFIX}ViewMore_Component`,
  ProductCategoryListingComponent: `${KEY_PREFIX}ProductCategoryListing_Component`,
  ProductCategoryListingOverrideComponent: `${KEY_PREFIX}ProductCategoryListingOverride_Component`,
} as const;
