import { KEY_PREFIX } from "../constants";

// This is in separate file to avoid circular reference when pushing types
// Otherwise there's a confusing error about object is not iterable when doing an Opti push

export const AllComponentTypeKeyMap = {
  HeroComponent: `${KEY_PREFIX}Hero_Component`,
  ContentBlockComponent: `${KEY_PREFIX}ContentBlock_Component`,
  CtaLinkListComponent: `${KEY_PREFIX}CtaLinkList_Component`,
  CtaButtonListComponent: `${KEY_PREFIX}CtaButtonList_Component`,
  AccordionComponent: `${KEY_PREFIX}Accordion_Component`,
  AccordionPanelComponent: `${KEY_PREFIX}AccordionPanel_Component`,
  CardListComponent: `${KEY_PREFIX}CardList_Component`,
  SingleGeneralCardComponent: `${KEY_PREFIX}GeneralCard_Component`,
  GeneralCardsComponent: `${KEY_PREFIX}GeneralCards_Component`,
  ProductCardsComponent: `${KEY_PREFIX}ProductCards_Component`,
  CodeEmbedComponent: `${KEY_PREFIX}CodeEmbed_Component`,
  CodeSnippetComponent: `${KEY_PREFIX}CodeSnippet_Component`,
  HomePageHeroSlideComponent: `${KEY_PREFIX}HomePageHeroSlide_Component`,
  HomePageHeroComponent: `${KEY_PREFIX}HomePageHero_Component`,
  ColumnGridColumnComponent: `${KEY_PREFIX}ColumnGridColumn_Component`,
  ColumnGridComponent: `${KEY_PREFIX}ColumnGrid_Component`,
  NewProductsCardListComponent: `${KEY_PREFIX}NewProductsCardList_Component`,
  StandardImageComponent: `${KEY_PREFIX}StandardImage_Component`,
  HeadshotImageComponent: `${KEY_PREFIX}HeadshotImage_Component`,
  HorizontalRuleComponent: `${KEY_PREFIX}HorizontalRule_Component`,
  VideoPlayerComponent: `${KEY_PREFIX}VideoPlayer_Component`,
  SelectionToolComponent: `${KEY_PREFIX}SelectionTool_Component`,
  PremiumMediaHeadingComponent: `${KEY_PREFIX}PremiumMediaHeading_Component`,
  ApplicationSearchBoxComponent: `${KEY_PREFIX}ApplicationSearchBox_Component`,
  FAQSearchBoxComponent: `${KEY_PREFIX}FAQSearchBox_Component`,
  BrowseVideosComponent: `${KEY_PREFIX}BrowseVideos_Component`,
  HierarchyNavigationComponent: `${KEY_PREFIX}HierarchyNavigation_Component`,
  HierarchyNavigationItemComponent: `${KEY_PREFIX}HierarchyNavigationItem_Component`,
  TabsComponent: `${KEY_PREFIX}Tabs_Component`,
  GeneralTabComponent: `${KEY_PREFIX}GeneralTab_Component`,
  JumpLinkNavigationComponent: `${KEY_PREFIX}JumpLinkNavigation_Component`,
  JumpLinkTargetComponent: `${KEY_PREFIX}JumpLinkTarget_Component`,
  GoldenSourcePageHeading: `${KEY_PREFIX}GoldenSourcePageHeading_Component`,
  ApiSwaggerComponent:`${KEY_PREFIX}ApiSwagger_Component`,
};
